### ISSUE TITLE
New option: Symbol.last

### ISSUE THREAD

**Issue by robpalme** [keithamus/proposal-array-last#2]
Given that Option 1 suffers from accidental creation of the meta index (`-1`), how about introducing a well-known symbol `Symbol.last` that has the same meaning?  It seems to have most of the pros and none of the cons.

`var lastElement = myArray[Symbol.last]`

**Comment by ljharb** [comment]
It would avoid any web compat risk, but a downside is that it's unfortunate (even tho not without precedent) to have a well-known symbol that only applies to one type of object.

**Comment by keithamus** [comment]
Yes right now the well known symbols fall very heavily in the "meta" domain. Perhaps this would feel more natural with the [Protocols proposal](https://github.com/michaelficarra/proposal-first-class-protocols)

**Comment by keithamus** [comment]
Closing this. The Readme has been updated to reflect the current state of this proposal which features `Array.prototype.end` getter/setter.

**Comment by dy** [comment]
> a well-known symbol that only applies to one type of object.

Why one type? Symbol seems to be more flexible/customizable for an arbitrary class/object, also avoids (high) performance cost - _lastItem_ does not make sense for array if it's more expensive than just `a[a.length - 1]`, and ideally it can be even faster (by keeping reference rather than prop access + op + index access).
